version: '3'

services:
  arayadev_nginx:
    image: nginx
    build: .
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    volumes:
      - "./blog.araya.dev:/var/www/araya.dev/blog.araya.dev"
      - "./www.araya.dev:/var/www/araya.dev/www.araya.dev"
      - "./playground.araya.dev:/var/www/araya.dev/playground.araya.dev"
      - "./logs:/var/logs"
      - "./conf/nginx/nginx.local.conf:/etc/nginx/nginx.conf"
      - "./conf/nginx/share:/etc/nginx/share"
