.PHONY:	build
build:
	rm -rf dist && deno run --allow-run --allow-read --allow-write --unstable build/build.tsx

.PHONY:	watch
watch:
	rm -rf dist && deno run --allow-run --allow-read --allow-write --unstable build/watch.ts
