name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-blog:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SERVER_IP: 52.69.164.172
      SSH_USER: ubuntu
      REMOTE_ROOT: /var/www/araya.dev
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Node.js env
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: |
            pnpm-lock.yaml
            blog.araya.dev/pnpm-lock.yaml
      - name: Build blog
        working-directory: ./blog.araya.dev
        run: |
          corepack enable
          corepack prepare pnpm@10.15.1 --activate
          pnpm install --frozen-lockfile
          pnpm build:prod
      - name: Setup SSH keys
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${SERVER_IP} >> ~/.ssh/known_hosts
          echo -e "$SSH_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
      - name: Deploy all
        run: |
          rsync --exclude "**/node_modules" --delete -r -e "ssh -i ~/.ssh/key" ./ ${SSH_USER}@${SERVER_IP}:${REMOTE_ROOT}/
