name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy-blog:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SERVER_IP: 52.69.164.172
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7.0.1
      - name: Setup Node.js env
        uses: actions/setup-node@v2.4.0
        with:
          node-version-file: .nvmrc
      - name: Build blog
        working-directory: ./blog.araya.dev
        run: |
          pnpm install 
          pnpm build
      - name: Setup SSH keys
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${SERVER_IP} >> ~/.ssh/known_hosts
          echo -e "$SSH_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
      - name: Deploy all
        run: |
          rsync --exclude "**/node_modules" --delete -r -e "ssh -i ~/.ssh/key" ./ ubuntu@${SERVER_IP}:/var/www/araya.dev/
