name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-blog:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js env
      uses: actions/setup-node@v2.4.0
      with:
        node-version: 16
        check-latest: true
    - name: Build blog
      workikng-directory: ./blog.araya.dev
      run: |
        yarn
        yarn run build
        
